"use client";

import { useId, useRef, type KeyboardEvent, type ReactNode } from "react";
import { Icon, type IconName } from "@/components/finance/ui/icon";

/**
 * The id prefix shared by a tab and its panel. Generated by the caller and passed to both `Tabs` and
 * `TabPanel`, because `aria-controls` and `aria-labelledby` have to point at each other and a value
 * created inside either component could not be seen by the other.
 */
export function useTabIds(): string {
  return useId();
}

export type TabItem<Id extends string = string> = {
  id: Id;
  label: string;
  icon?: IconName;
  /** Small trailing count, e.g. the number of rows behind the tab. */
  badge?: string;
  description?: string;
};

type TabsProps<Id extends string> = {
  items: ReadonlyArray<TabItem<Id>>;
  active: Id;
  onChange: (id: Id) => void;
  label: string;
  /** From `useTabIds()`. Pass the same value to every matching `TabPanel`. */
  idBase: string;
  orientation?: "horizontal" | "vertical";
  className?: string;
};

/**
 * Tab list with the full keyboard contract: one tab stop for the whole set (roving `tabindex`),
 * arrow keys to move between tabs, Home/End to jump to either end. That is what the ARIA tabs
 * pattern requires, and it is the reason this is a component rather than a row of buttons — a
 * hand-rolled tab strip almost always leaves every tab in the tab order, which turns a five-section
 * settings page into five extra stops before the content.
 *
 * Panels are rendered by the caller with `<TabPanel>`, sharing the same `idBase`.
 */
export function Tabs<Id extends string>({
  items,
  active,
  onChange,
  label,
  idBase,
  orientation = "horizontal",
  className = "",
}: TabsProps<Id>) {
  const refs = useRef(new Map<Id, HTMLButtonElement>());

  const move = (event: KeyboardEvent<HTMLDivElement>) => {
    const index = items.findIndex((item) => item.id === active);
    if (index < 0) return;

    // Both axes are accepted whatever the orientation. The settings rail is vertical on desktop and a
    // horizontal scroller on phones — the same element either way — so binding only one axis would
    // leave arrow keys pointing the wrong way at one of the two sizes.
    let next = index;
    if (event.key === "ArrowDown" || event.key === "ArrowRight") next = (index + 1) % items.length;
    else if (event.key === "ArrowUp" || event.key === "ArrowLeft") next = (index - 1 + items.length) % items.length;
    else if (event.key === "Home") next = 0;
    else if (event.key === "End") next = items.length - 1;
    else return;

    event.preventDefault();
    const target = items[next];
    onChange(target.id);
    refs.current.get(target.id)?.focus();
  };

  const vertical = orientation === "vertical";

  return (
    <div
      role="tablist"
      aria-label={label}
      aria-orientation={orientation}
      onKeyDown={move}
      className={
        vertical
          ? `flex flex-col gap-0.5 ${className}`
          : `finance-scroll -mx-4 flex gap-1 overflow-x-auto px-4 sm:mx-0 sm:px-0 ${className}`
      }
    >
      {items.map((item) => {
        const selected = item.id === active;
        return (
          <button
            key={item.id}
            ref={(node) => {
              if (node) refs.current.set(item.id, node);
              else refs.current.delete(item.id);
            }}
            type="button"
            role="tab"
            id={tabId(idBase, item.id)}
            aria-selected={selected}
            aria-controls={tabPanelId(idBase, item.id)}
            tabIndex={selected ? 0 : -1}
            onClick={() => onChange(item.id)}
            className={
              vertical
                ? `flex w-full items-center gap-2.5 rounded-md px-3 py-2.5 text-left text-[13.5px] transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0d4d3b] ${
                    selected
                      ? "bg-[#eef2ec] font-semibold text-[#0b4634] shadow-[inset_2px_0_0_#0d4d3b]"
                      : "font-medium text-[#4d564f] hover:bg-[#f4f3ec] hover:text-[#17211d]"
                  }`
                : `inline-flex shrink-0 items-center gap-2 rounded-md border px-3 py-2 text-[13px] transition-colors focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0d4d3b] ${
                    selected
                      ? "border-[#0d4d3b] bg-[#0d4d3b] font-semibold text-white"
                      : "border-transparent font-medium text-[#4d564f] hover:bg-[#f2f1ea] hover:text-[#17211d]"
                  }`
            }
          >
            {item.icon ? (
              <Icon
                name={item.icon}
                size={16}
                className={selected ? (vertical ? "text-[#0d4d3b]" : "text-[#e0be79]") : "opacity-70"}
              />
            ) : null}
            <span className="min-w-0 flex-1 truncate">{item.label}</span>
            {item.badge ? (
              <span
                className={`shrink-0 rounded-full px-1.5 py-0.5 text-[10.5px] font-bold tabular-nums ${
                  selected
                    ? vertical
                      ? "bg-[#0d4d3b] text-white"
                      : "bg-white/20 text-white"
                    : "bg-[#eceadf] text-[#5c655f]"
                }`}
              >
                {item.badge}
              </span>
            ) : null}
          </button>
        );
      })}
    </div>
  );
}

/**
 * The ids `Tabs` generates, exposed so a caller's panel can carry the matching `id` and
 * `aria-labelledby`. Both take the value from `useTabIds()`.
 */
export function tabId(base: string, id: string): string {
  return `${base}-tab-${id}`;
}

export function tabPanelId(base: string, id: string): string {
  return `${base}-panel-${id}`;
}

/** Panel for one tab, correctly associated with it. Renders nothing when its tab is not selected. */
export function TabPanel({
  base,
  id,
  active,
  children,
  className = "",
}: {
  base: string;
  id: string;
  active: boolean;
  children: ReactNode;
  className?: string;
}) {
  if (!active) return null;
  return (
    <div
      role="tabpanel"
      id={tabPanelId(base, id)}
      aria-labelledby={tabId(base, id)}
      tabIndex={0}
      className={`finance-enter focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#0d4d3b] ${className}`}
    >
      {children}
    </div>
  );
}
