"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { IslamicTexture } from "@/components/islamic-texture";
import { useLanguage } from "@/components/language-provider";
import { getAudioUrl, surahs, type Revelation, type Surah } from "@/components/quran/quran-data";

function SurahCard({ surah, language, onPlay }: { surah: Surah; language: "en" | "bn"; onPlay: (surah: Surah) => void }) {
  const bengali = language === "bn";
  return <article className="group border border-[#deddd3] bg-white p-5 transition duration-300 hover:-translate-y-1 hover:border-[#c79a45] hover:shadow-[0_14px_35px_rgba(7,58,45,.1)]"><div className="flex items-start justify-between gap-4"><span className="text-sm font-bold tracking-[.15em] text-[#c79a45]">{String(surah.number).padStart(2, "0")}</span><span className="text-right text-2xl text-[#0d4d3b]" lang="ar" dir="rtl">{surah.arabic}</span></div><div className="mt-6 flex items-end justify-between gap-4"><div><h3 className="text-xl font-semibold">{bengali ? surah.english : surah.english}</h3><p className="mt-1 text-sm text-[#69726d]">{bengali ? surah.meaning : surah.meaning} · {surah.ayahs} {bengali ? "আয়াত" : "Ayahs"}</p><span className="mt-3 inline-block text-[10px] font-bold uppercase tracking-[.16em] text-[#c79a45]">{surah.revelation}</span></div><div className="flex gap-2"><button type="button" onClick={() => onPlay(surah)} className="grid h-9 w-9 place-items-center border border-[#c79a45] text-[#0d4d3b]" aria-label={`${bengali ? "শুনুন" : "Listen to"} ${surah.english}`}>▷</button><Link href={`/quran/${surah.slug}`} className="grid h-9 w-9 place-items-center bg-[#0d4d3b] text-white" aria-label={`${bengali ? "পড়ুন" : "Read"} ${surah.english}`}>↗</Link></div></div></article>;
}

export function QuranPage() {
  const { language } = useLanguage();
  const bengali = language === "bn";
  const [query, setQuery] = useState("");
  const [revelation, setRevelation] = useState<"All" | Revelation>("All");
  const [playing, setPlaying] = useState<Surah | null>(null);
  const filtered = useMemo(() => surahs.filter((surah) => { const haystack = `${surah.number} ${surah.english} ${surah.arabic} ${surah.meaning}`.toLowerCase(); return haystack.includes(query.toLowerCase()) && (revelation === "All" || surah.revelation === revelation); }), [query, revelation]);
  const featured = surahs[17];

  return <div>
    <section className="relative overflow-hidden bg-[#073a2d] px-5 pb-20 pt-36 text-white"><IslamicTexture variant="hero" position="left" className="-left-45 top-16 h-150 w-135 bg-contain opacity-10" /><div className="relative z-10 mx-auto max-w-7xl lg:px-8"><p className="text-xs font-bold tracking-[.22em] text-[#e0be79]">{bengali ? "নূর কমিউনিটি মসজিদ · আল-কুরআন" : "NOOR COMMUNITY MOSQUE · AL-QURAN"}</p><h1 className="mt-4 max-w-3xl text-5xl font-semibold leading-tight sm:text-7xl">{bengali ? "পবিত্র কুরআন।" : "The Holy Quran."}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/70">{bengali ? "আল্লাহর বাণী পড়ুন, শুনুন এবং চিন্তা করুন। আরবি পাঠের সঙ্গে বাংলা ও ইংরেজি অনুবাদ অন্বেষণ করুন।" : "Read, listen and reflect on the words of Allah with Arabic text and translations in English and Bangla."}</p><p className="mt-8 text-sm tracking-[.2em] text-[#e0be79]">READ · LISTEN · REFLECT</p></div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="grid gap-5 lg:grid-cols-[1.4fr_.6fr_.6fr]"><div className="border border-[#0d4d3b] bg-[#0d4d3b] p-7 text-white"><p className="text-xs font-bold tracking-[.2em] text-[#e0be79]">{bengali ? "আপনার যাত্রা শুরু করুন" : "BEGIN YOUR JOURNEY"}</p><h2 className="mt-4 text-3xl font-semibold">{bengali ? "সূরা আল-ফাতিহা দিয়ে শুরু করুন।" : "Start with Surah Al-Fatihah."}</h2><div className="mt-7 h-1 bg-white/20"><div className="h-full w-1/12 bg-[#c79a45]" /></div><Link href="/quran/al-fatihah" className="mt-6 inline-block bg-[#c79a45] px-5 py-3 font-semibold text-[#153128]">{bengali ? "পড়া শুরু করুন" : "Start Reading"} ↗</Link></div><button type="button" onClick={() => setPlaying(featured)} className="border border-[#deddd3] bg-white p-7 text-left transition hover:border-[#c79a45]"><span className="text-3xl text-[#c79a45]">▷</span><h2 className="mt-5 text-xl font-semibold">{bengali ? "কুরআন শুনুন" : "Listen to Quran"}</h2><p className="mt-2 text-sm text-[#69726d]">{bengali ? "শান্তভাবে তিলাওয়াত শুনুন।" : "Let the recitation accompany your day."}</p></button><a href="#find-surah" className="border border-[#deddd3] bg-white p-7 transition hover:border-[#c79a45]"><span className="text-3xl text-[#c79a45]">⌕</span><h2 className="mt-5 text-xl font-semibold">{bengali ? "সূরা খুঁজুন" : "Search Quran"}</h2><p className="mt-2 text-sm text-[#69726d]">{bengali ? "নাম বা নম্বর দিয়ে খুঁজুন।" : "Find by name or number."}</p></a></div></section>

    <section id="find-surah" className="bg-[#ecece3] px-5 py-16"><div className="mx-auto max-w-7xl lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-[#c79a45]">{bengali ? "একটি সূরা খুঁজুন" : "FIND A SURAH"}</p><h2 className="mt-3 text-4xl font-semibold">{bengali ? "কুরআনের সঙ্গে আপনার সময়।" : "Make time for the Quran."}</h2><div className="mt-7 flex flex-col gap-3 md:flex-row"><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder={bengali ? "নাম, আরবি বা নম্বর দিয়ে খুঁজুন..." : "Search by Surah name, Arabic or number..."} className="min-w-0 flex-1 border border-[#cfcfc3] bg-white px-4 py-3 outline-none focus:border-[#0d4d3b]" /><div className="flex gap-2"><button type="button" onClick={() => setRevelation("All")} className={`border px-4 py-3 text-sm font-semibold ${revelation === "All" ? "bg-[#0d4d3b] text-white" : "border-[#cfcfc3] bg-white"}`}>{bengali ? "সব" : "All"}</button><button type="button" onClick={() => setRevelation("Meccan")} className={`border px-4 py-3 text-sm font-semibold ${revelation === "Meccan" ? "bg-[#0d4d3b] text-white" : "border-[#cfcfc3] bg-white"}`}>Meccan</button><button type="button" onClick={() => setRevelation("Medinan")} className={`border px-4 py-3 text-sm font-semibold ${revelation === "Medinan" ? "bg-[#0d4d3b] text-white" : "border-[#cfcfc3] bg-white"}`}>Medinan</button></div></div><div className="mt-10 flex items-end justify-between"><div><p className="text-xs font-bold tracking-[.2em] text-[#c79a45]">{bengali ? "সূরা" : "SURAHS"}</p><h2 className="mt-2 text-3xl font-semibold">114 {bengali ? "অধ্যায়" : "chapters"}</h2></div><span className="text-sm text-[#69726d]">{filtered.length} {bengali ? "দেখানো হচ্ছে" : "shown"}</span></div><div className="mt-7 grid gap-4 md:grid-cols-2">{filtered.map((surah) => <SurahCard key={surah.number} surah={surah} language={language} onPlay={setPlaying} />)}</div>{!filtered.length && <p className="mt-7 bg-white p-8 text-center text-[#69726d]">{bengali ? "কোনো সূরা পাওয়া যায়নি।" : "No Surahs found."}</p>}</div></section>

    <section className="mx-auto max-w-7xl px-5 py-16 lg:px-8"><div className="border-y border-[#deddd3] py-12 text-center"><p className="text-xs font-bold tracking-[.2em] text-[#c79a45]">{bengali ? "বিশেষ সূরা" : "FEATURED SURAH"}</p><p className="mt-6 text-4xl text-[#0d4d3b]" lang="ar" dir="rtl">{featured.arabic}</p><h2 className="mt-3 text-3xl font-semibold">{featured.english}</h2><p className="mt-2 text-[#69726d]">{bengali ? "শুক্রবার পাঠের জন্য প্রিয় একটি সূরা।" : "A beloved Surah traditionally recited on Fridays."}</p><div className="mt-6 flex justify-center gap-3"><Link href={`/quran/${featured.slug}`} className="bg-[#0d4d3b] px-5 py-3 font-semibold text-white">{bengali ? "সূরা পড়ুন" : "Read Surah"} ↗</Link><button type="button" onClick={() => setPlaying(featured)} className="border border-[#0d4d3b] px-5 py-3 font-semibold text-[#0d4d3b]">{bengali ? "শুনুন" : "Listen"} ▷</button></div></div></section>

    <section className="bg-[#ecece3] px-5 py-16"><div className="mx-auto max-w-7xl lg:px-8"><p className="text-xs font-bold tracking-[.2em] text-[#c79a45]">{bengali ? "কুরআন শিখুন" : "LEARN THE QURAN"}</p><h2 className="mt-3 text-4xl font-semibold">{bengali ? "কুরআনের সঙ্গে সম্পর্ক বাড়ান।" : "Grow your connection with the Quran."}</h2><div className="mt-8 grid gap-5 md:grid-cols-2"><Link href="/services/quran-classes" className="bg-white p-7 transition hover:shadow-lg"><h3 className="text-2xl font-semibold">{bengali ? "কুরআন ক্লাস" : "Quran Classes"}</h3><p className="mt-3 leading-7 text-[#69726d]">{bengali ? "পড়া, তাজবিদ ও তিলাওয়াত শিখুন।" : "Learn reading, Tajweed and recitation."}</p><span className="mt-6 inline-block font-semibold text-[#0d4d3b]">{bengali ? "অন্বেষণ করুন" : "Explore"} ↗</span></Link><Link href="/services/islamic-studies" className="bg-white p-7 transition hover:shadow-lg"><h3 className="text-2xl font-semibold">{bengali ? "তাজবিদ" : "Tajweed"}</h3><p className="mt-3 leading-7 text-[#69726d]">{bengali ? "উচ্চারণ ও তিলাওয়াত উন্নত করুন।" : "Improve your pronunciation and recitation."}</p><span className="mt-6 inline-block font-semibold text-[#0d4d3b]">{bengali ? "আরও জানুন" : "Learn more"} ↗</span></Link></div></div></section>

    {playing && <div className="fixed inset-x-0 bottom-0 z-40 border-t border-white/10 bg-[#073a2d] px-5 py-4 text-white shadow-[0_-10px_30px_rgba(0,0,0,.2)]"><div className="mx-auto flex max-w-7xl items-center gap-4 lg:px-8"><button type="button" onClick={() => setPlaying(null)} className="text-white/60" aria-label="Close audio player">×</button><div className="min-w-0 flex-1"><p className="font-semibold">{playing.english}</p><audio controls autoPlay src={getAudioUrl(playing.number)} className="mt-2 h-8 w-full" /></div></div></div>}
  </div>;
}
